#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------

# Which carpentry is this (swc, dc, lc, or cp)?
# swc: Software Carpentry
# dc: Data Carpentry
# lc: Library Carpentry
# cp: Carpentries (to use for instructor training for instance)
# incubator: The Carpentries Incubator
carpentry: 'incubator'

# Overall title for pages.
title: 'Git and GitHub Working Practices'

# Date the lesson was created (YYYY-MM-DD, this is empty by default)
created: '2024-11-11'

# Comma-separated list of keywords for the lesson
keywords: 'software, data, lesson, The Carpentries, Git, GitHub'

# Life cycle stage of the lesson
# possible values: pre-alpha, alpha, beta, stable
life_cycle: 'stable'

# License of the lesson materials (recommended CC-BY 4.0)
license: 'CC-BY 4.0'

# Link to the source repository for this lesson
source: 'https://github.com/metoffice/git-working-practices'

# Default branch of your lesson
branch: 'main'

# Who to contact if there are any issues
contact: 'd.theodorakis@metoffice.gov.uk'

# Navigation ------------------------------------------------
#
# Use the following menu items to specify the order of
# individual pages in each dropdown section. Leave blank to
# include all pages in the folder.

# Order of episodes in your lesson
episodes:
- 00-repo-access.md
- 01-issues.md
- 02-branching.md
- 03-feature-branch.md
- 04-review.md
- Break.md
- 07-history.md
- 05-forks.md
- 06-conflict.md
- End.md
- 08-rebase.md
- 09-pre-commit.md

# Information for Learners
learners:
- discuss.md
- reference.md
- feature-branch-dev.md
- forking-dev.md
- fcm-git_cheat_sheet.md

# Information for Instructors
instructors:

# Learner Profiles
profiles:

# Customisation ---------------------------------------------
#
# This space below is where custom yaml items (e.g. pinning
# sandpaper and varnish versions) should live

sandpaper: astroDimitrios/sandpaper
varnish: astroDimitrios/varnish

url: 'https://metoffice.github.io/git-working-practices'
analytics: carpentries
lang: en
